# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v2
#     - name: Use Node.js 14.17.6
#       uses: actions/setup-node@v2
#       with:
#         node-version: 14.17.6
#         cache: 'npm'
#     - run: npm install
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
    - name: build docker images
      run: |
        docker build . --tag ghcr.io/int222-ecatalog-project/front-end
        docker images 
    - name: push docker image to registy
      run: |
        docker push ghcr.io/int222-ecatalog-project/front-end
